apiVersion: 1

datasources:
  - name: SSH Logs
    type: marcusolsson-json-datasource
    access: proxy
    url: http://log-server:8080
    isDefault: true
    editable: true
    jsonData:
      cacheDurationSeconds: 30
  
  - name: Web Logs
    type: marcusolsson-json-datasource
    access: proxy
    url: http://log-server:8080
    editable: true
    jsonData:
      cacheDurationSeconds: 30
