apiVersion: 1

datasources:
  - name: SSH Logs
    type: marcusolsson-json-datasource
    access: proxy
    url: file:///var/log/honeypot
    isDefault: true
    editable: true
    jsonData:
      cacheDurationSeconds: 60
  
  - name: Web Logs
    type: marcusolsson-json-datasource
    access: proxy
    url: file:///var/log/honeypot
    editable: true
    jsonData:
      cacheDurationSeconds: 60
