apiVersion: 1

datasources:
  - name: JSON Logs
    type: marcusolsson-json-datasource
    access: proxy
    url: file:///var/log/honeypot
    isDefault: true
    editable: true
    jsonData:
      path: "*.json"
